include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    always_use_package_imports: false
    prefer_relative_imports: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    flutter_style_todos: false
    one_member_abstracts: false
    always_put_required_named_parameters_first: false
    unnecessary_raw_strings: false
    missing_whitespace_between_adjacent_strings: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_positional_boolean_parameters: false
